### ISSUE TITLE
lib build 有 less 时有问题 

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi-plugin-library#26]
## 报错

```bash
bundle error { Error: Cannot find module 'less'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at resolveFileName (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/resolve-from/index.js:31:9)
    at module.exports (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/resolve-from/index.js:34:41)
    at module.exports (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/import-from/index.js:4:49)
    at module.exports.moduleId (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/import-cwd/index.js:4:30)
    at Object.<anonymous> (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/rollup-plugin-postcss/dist/rollup-plugin-postcss.cjs.js:322:14)
    at new Promise (<anonymous>)
    at Object.process (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/rollup-plugin-postcss/dist/rollup-plugin-postcss.cjs.js:317:12)
    at v (/Users/chencheng/Code/github.com/umijs/umi-plugin-library/packages/umi-plugin-library/node_modules/rollup-plugin-postcss/dist/rollup-plugin-postcss.cjs.js:424:33)
  code: 'PLUGIN_ERROR',
  pluginCode: 'MODULE_NOT_FOUND',
  plugin: 'postcss',
  hook: 'transform',
  id: '/private/tmp/sorrycc-qcu3LQ/src/index.less' }
```

## 猜测原因

rollup-plugin-postcss 找 less 模块是从当前路径开始找的，见 https://github.com/egoist/rollup-plugin-postcss/blob/master/src/less-loader.js#L9 。如果 less 没有被 hoist 到最上层，就会找不到了。

## 复现步骤

1. 用 yarn bootstrap 这个仓库
2. link 使用
3. 项目里有依赖 less 文件

**Comment by clock157** [comment]
没有重现成功，使用的是 umi-create 创建的那个应用，可能需要更多的细节。

**Comment by clock157** [comment]
这个问题还能复现吗 @sorrycc
