### ISSUE TITLE
autoNamedExports这个插件对于某些包有问题的

### ISSUE THREAD

**Issue by sciice** [umijs/umi-plugin-library#41]
比如axios. 报错信息如下。
````
$ umi lib build
bundle error { Error: Duplicate export 'headers'
    at error (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:3597:30)
    at Module.error (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:14375:9)
    at tryParse (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:14038:16)
    at Module.setSource (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:14094:35)
    at /Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:17407:20
  code: 'PARSE_ERROR',
  pos: 3859,
  loc:
   { file:
      '/Users/ben/Desktop/component/node_modules/axios/lib/defaults.js',
     line: 139,
     column: 26 },
  frame: '' }
bundle error { Error: Duplicate export 'headers'
    at error (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:3597:30)
    at Module.error (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:14375:9)
    at tryParse (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:14038:16)
    at Module.setSource (/Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:14094:35)
    at /Users/ben/Desktop/component/node_modules/rollup/dist/rollup.js:17407:20
  code: 'PARSE_ERROR',
  pos: 3859,
  loc:
   { file:
      '/Users/ben/Desktop/component/node_modules/axios/lib/defaults.js',
     line: 139,
     column: 26 },
  frame: '' }
✔  success   [@contain/component] cjs: dist/component.js
✔  success   [@contain/component] esm: dist/component.esm.js
````

是否考虑可设置是否启用此插件？

**Comment by clock157** [comment]
可以的，目前来看是这个 `axios` 有未覆盖到的场景，我稍后排查下，你先可以将 axios 设为 external。
另外你的组件是什么类型的，ui 组件还是 纯 library 库，需要用到网络库吗？

**Comment by sciice** [comment]
需要用到的，目前基于UMI的monorepo方式，网络库需要统一做一些配置然后打包成公用库供其他模块使用的。

**Comment by clock157** [comment]
那我跟进下，另外，你们的库是否需要支持 umd 呢，也就是支持浏览器加载？如果不需要，可以 `umd: false` 不打 umd。

**Comment by sciice** [comment]
需要，用umi的monorepo方式须得用umd来加载子模块

**Comment by clock157** [comment]
那我再安利一下 `umi-request` 吧，有什么需求可以支持哈。

**Comment by clock157** [comment]
已修复 auto named exports 并支持关掉，等明天发包就可以了。
